# site settings
title: Promotito
subtitle: Melbourne, Australia
email: team@eatrepeat.com.au
description: Increase program engagement using dynamic, automated, text-based conversations
baseurl: # the subpath of your site, e.g. /blog
url: https://jaohar.github.io # the base hostname & protocol for your site
author: Jonathan
street_address: Brunswick Road
city: Melbourne
state: Victoria
zip_code: 3056
country: Australia
phone: +61 4XX XXX XXX

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 9 # first page counts as two tiles (add two to tile number)

# social settings

youtube_url: https://xyz.com
instagram_url:
facebook_url: https://xyz.com
github_url:
gitlab_url: 
googleplus_url:
500px_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
