# site settings
title: Butts4Life
subtitle: by DumiDumi Corporation
email: olivia@dumidumi.com
description: We make good bideos with food<br/> sometimes with Pebbles and Sir Loris.
baseurl: # the subpath of your site, e.g. /blog
url: https://jaohar.github.io # the base hostname & protocol for your site
author: King Dumi
street_address: Brunswick Road
city: Melbourne
state: Victoria
zip_code: 3056
country: Australia
phone: +61 4XX XXX XXX

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings

youtube_url: https://instagram.com
instagram_url: https://instagram.com
facebook_url: https://instagram.com
github_url:
gitlab_url: 
googleplus_url:
500px_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
